	---acura
			['tltypes'] = {
				['name'] = 'tltypes',
				['brand'] = 'acura',
				['model'] = 'tltypes',
				['price'] = 34000,
				['category'] = 'import',
				['hash'] = `tltypes`,
				['shop'] = 'pdm',
			},
	---alfaromeo
			['155q4'] = {
				['name'] = '155q4',
				['brand'] = 'alfaromeo',
				['model'] = '155q4',
				['price'] = 20000,
				['category'] = 'import',
				['hash'] = `155q4`,
				['shop'] = 'pdm',
			},
			['giuliasuper'] = {
				['name'] = 'giuliasuper',
				['brand'] = 'alfaromeo',
				['model'] = 'giuliasuper',
				['price'] = 40000,
				['category'] = 'import',
				['hash'] = `giuliasuper`,
				['shop'] = 'pdm',
			},
			['stelvio'] = {
				['name'] = 'stelvio',
				['brand'] = 'alfaromeo',
				['model'] = 'stelvio',
				['price'] = 87000,
				['category'] = 'import',
				['hash'] = `stelvio`,
				['shop'] = 'pdm',
			},
	---astonmartin		
			['ast'] = {
				['name'] = 'ast',
				['brand'] = 'astonmartin',
				['model'] = 'ast',
				['price'] = 280000,
				['category'] = 'import',
				['hash'] = `ast`,
				['shop'] = 'pdm',
			},
			['cyrus'] = {
				['name'] = 'cyrus',
				['brand'] = 'astonmartin',
				['model'] = 'cyrus',
				['price'] = 600000,
				['category'] = 'import',
				['hash'] = `cyrus`,
				['shop'] = 'pdm',
			},
	---audi		
			['2013rs7'] = {
				['name'] = '2013rs7',
				['brand'] = 'audi',
				['model'] = '2013rs7',
				['price'] = 115000,
				['category'] = 'import',
				['hash'] = `2013rs7`,
				['shop'] = 'pdm',
			},
			['2015s3'] = {
				['name'] = '2015s3',
				['brand'] = 'audi',
				['model'] = '2015s3',
				['price'] = 47000,
				['category'] = 'import',
				['hash'] = `2015s3`,
				['shop'] = 'pdm',
			},
			['audquattros'] = {
				['name'] = 'audquattros',
				['brand'] = 'audi',
				['model'] = 'audquattros',
				['price'] = 49000,
				['category'] = 'import',
				['hash'] = `audquattros`,
				['shop'] = 'pdm',
			},
			['rmodrs6'] = {
				['name'] = 'rmodrs6',
				['brand'] = 'audi',
				['model'] = 'rmodrs6',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `rmodrs6`,
				['shop'] = 'pdm',
			},
			['rs3'] = {
				['name'] = 'rs3',
				['brand'] = 'audi',
				['model'] = 'rs3',
				['price'] = 58000,
				['category'] = 'import',
				['hash'] = `rs3`,
				['shop'] = 'pdm',
			},
			['sjaudi'] = {
				['name'] = 'sjaudi',
				['brand'] = 'audi',
				['model'] = 'sjaudi',
				['price'] = 4000,
				['category'] = 'import',
				['hash'] = `sjaudi`,
				['shop'] = 'pdm',
			},
			['tts'] = {
				['name'] = 'tts',
				['brand'] = 'audi',
				['model'] = 'tts',
				['price'] = 65000,
				['category'] = 'import',
				['hash'] = `tts`,
				['shop'] = 'pdm',
			},
	---bentley		
			['bbentayga'] = {
				['name'] = 'bbentayga',
				['brand'] = 'bentley',
				['model'] = 'bbentayga',
				['price'] = 180000,
				['category'] = 'import',
				['hash'] = `bbentayga`,
				['shop'] = 'pdm',
			},
			['ben17'] = {
				['name'] = 'ben17',
				['brand'] = 'bentley',
				['model'] = 'ben17',
				['price'] = 200000,
				['category'] = 'import',
				['hash'] = `ben17`,
				['shop'] = 'pdm',
			},
			['contgt2011'] = {
				['name'] = 'contgt2011',
				['brand'] = 'bentley',
				['model'] = 'contgt2011',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `contgt2011`,
				['shop'] = 'pdm',
			},
			['contss18'] = {
				['name'] = 'contss18',
				['brand'] = 'bentley',
				['model'] = 'contss18',
				['price'] = 270000,
				['category'] = 'import',
				['hash'] = `contss18`,
				['shop'] = 'pdm',
			},
    ---bicycle			
			['bfixter'] = {
				['name'] = 'bfixter',
				['brand'] = 'bicycle',
				['model'] = 'bfixter',
				['price'] = 4000,
				['category'] = 'import',
				['hash'] = `bfixter`,
				['shop'] = 'pdm',
			},
			['bmxP2'] = {
				['name'] = 'bmxP2',
				['brand'] = 'bicycle',
				['model'] = 'bmxP2',
				['price'] = 900,
				['category'] = 'import',
				['hash'] = `bmxP2`,
				['shop'] = 'pdm',
			},
	---bmw		
			['325et'] = {
				['name'] = '325et',
				['brand'] = 'bmw',
				['model'] = '325et',
				['price'] = 16000,
				['category'] = 'import',
				['hash'] = `325et`,
				['shop'] = 'pdm',
			},
			['440i'] = {
				['name'] = '440i',
				['brand'] = 'bmw',
				['model'] = '440i',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `440i`,
				['shop'] = 'pdm',
			},
			['750il'] = {
				['name'] = '750il',
				['brand'] = 'bmw',
				['model'] = '750il',
				['price'] = 60000,
				['category'] = 'police',
				['hash'] = `police`,
				['shop'] = 'pdm',
			},
			['bmci'] = {
				['name'] = 'bmci',
				['brand'] = 'bmw',
				['model'] = 'bmci',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `bmci`,
				['shop'] = 'pdm',
			},
			['bmw507'] = {
				['name'] = 'bmw507',
				['brand'] = 'bmw',
				['model'] = 'bmw507',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `bmw507`,
				['shop'] = 'pdm',
			},
			['bmwe3'] = {
				['name'] = 'bmwe3',
				['brand'] = 'bmw',
				['model'] = 'bmwe3',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `bmwe3`,
				['shop'] = 'pdm',
			},
			['e21'] = {
				['name'] = 'e21',
				['brand'] = 'bmw',
				['model'] = 'e21',
				['price'] = 24000,
				['category'] = 'import',
				['hash'] = `e21`,
				['shop'] = 'pdm',
			},
			['e92'] = {
				['name'] = 'e92',
				['brand'] = 'bmw',
				['model'] = 'e92',
				['price'] = 65000,
				['category'] = 'import',
				['hash'] = `e92`,
				['shop'] = 'pdm',
			},
			['f82'] = {
				['name'] = 'f82',
				['brand'] = 'bmw',
				['model'] = 'f82',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `f82`,
				['shop'] = 'pdm',
			},
			['m4c'] = {
				['name'] = 'm4c',
				['brand'] = 'bmw',
				['model'] = 'm4c',
				['price'] = 79000,
				['category'] = 'import',
				['hash'] = `m4c`,
				['shop'] = 'pdm',
			},
			['m5e28'] = {
				['name'] = 'm5e28',
				['brand'] = 'bmw',
				['model'] = 'm5e28',
				['price'] = 35000,
				['category'] = 'import',
				['hash'] = `m5e28`,
				['shop'] = 'pdm',
			},
			['m5e60'] = {
				['name'] = 'm5e60',
				['brand'] = 'bmw',
				['model'] = 'm5e60',
				['price'] = 69000,
				['category'] = 'import',
				['hash'] = `m5e60`,
				['shop'] = 'pdm',
			},
			['e92'] = {
				['name'] = 'm6f13',
				['brand'] = 'bmw',
				['model'] = 'm6f13',
				['price'] = 70000,
				['category'] = 'import',
				['hash'] = `m6f13`,
				['shop'] = 'pdm',
			},
			['e92'] = {
				['name'] = 'm8gte',
				['brand'] = 'bmw',
				['model'] = 'm8gte',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `m8gte`,
				['shop'] = 'pdm',
			},
			['rmodx6'] = {
				['name'] = 'rmodx6',
				['brand'] = 'bmw',
				['model'] = 'rmodx6',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `rmodx6`,
				['shop'] = 'pdm',
			},
	---bugatti		
			['alec'] = {
				['name'] = 'alec',
				['brand'] = 'bugatti',
				['model'] = 'alec',
				['price'] = 3000000,
				['category'] = 'import',
				['hash'] = `alec`,
				['shop'] = 'pdm',
			},
	---buick		
			['bgnx'] = {
				['name'] = 'bgnx',
				['brand'] = 'buick',
				['model'] = 'bgnx',
				['price'] = 42000,
				['category'] = 'import',
				['hash'] = `bgnx`,
				['shop'] = 'pdm',
			},
			['cnty'] = {
				['name'] = 'cnty',
				['brand'] = 'buick',
				['model'] = 'cnty',
				['price'] = 37000,
				['category'] = 'import',
				['hash'] = `cnty`,
				['shop'] = 'pdm',
			},
	---chevrolet		
			['c7'] = {
				['name'] = 'c7',
				['brand'] = 'chevrolet',
				['model'] = 'c7',
				['price'] = 120000,
				['category'] = 'import',
				['hash'] = `c7`,
				['shop'] = 'pdm',
			},
			['camaro90'] = {
				['name'] = 'camaro90',
				['brand'] = 'chevrolet',
				['model'] = 'camaro90',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `camaro90`,
				['shop'] = 'pdm',
			},
			['chevelle1970'] = {
				['name'] = 'chevelle1970',
				['brand'] = 'chevrolet',
				['model'] = 'chevelle1970',
				['price'] = 47000,
				['category'] = 'import',
				['hash'] = `chevelle1970`,
				['shop'] = 'pdm',
			},
			['impala59c'] = {
				['name'] = 'impala59c',
				['brand'] = 'chevrolet',
				['model'] = 'impala59c',
				['price'] = 49000,
				['category'] = 'import',
				['hash'] = `impala59c`,
				['shop'] = 'pdm',
			},
			['z2879'] = {
				['name'] = 'z2879',
				['brand'] = 'chevrolet',
				['model'] = 'z2879',
				['price'] = 44500,
				['category'] = 'import',
				['hash'] = `z2879`,
				['shop'] = 'pdm',
			},
	---dodge		
			['chargerf8'] = {
				['name'] = 'chargerf8',
				['brand'] = 'dodge',
				['model'] = 'e92',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `chargerf8`,
				['shop'] = 'pdm',
			},
			['demon'] = {
				['name'] = 'demon',
				['brand'] = 'dodge',
				['model'] = 'demon',
				['price'] = 97000,
				['category'] = 'import',
				['hash'] = `demon`,
				['shop'] = 'pdm',
			},
			['ram2500'] = {
				['name'] = 'ram2500',
				['brand'] = 'dodge',
				['model'] = 'ram2500',
				['price'] = 40000,
				['category'] = 'import',
				['hash'] = `ram2500`,
				['shop'] = 'pdm',
			},
			['redeye'] = {
				['name'] = 'redeye',
				['brand'] = 'dodge',
				['model'] = 'redeye',
				['price'] = 110000,
				['category'] = 'import',
				['hash'] = `redeye`,
				['shop'] = 'pdm',
			},
			['rt70'] = {
				['name'] = 'rt70',
				['brand'] = 'dodge',
				['model'] = 'rt70',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `rt70`,
				['shop'] = 'pdm',
			},
			['Viper'] = {
				['name'] = 'Viper',
				['brand'] = 'dodge',
				['model'] = 'Viper',
				['price'] = 140000,
				['category'] = 'import',
				['hash'] = `Viper`,
				['shop'] = 'pdm',
			},
	---ambulance		
			['ambulance22'] = {
				['name'] = 'ambulance22',
				['brand'] = 'ambulance',
				['model'] = 'ambulance22',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `ambulance22`,
				['shop'] = 'pdm',
			},
			['qrv'] = {
				['name'] = 'qrv',
				['brand'] = 'ambulance',
				['model'] = 'qrv',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `qrv`,
				['shop'] = 'pdm',
			},
	---ferrari		
			['412'] = {
				['name'] = '412',
				['brand'] = 'ferrari',
				['model'] = '412',
				['price'] = 85000,
				['category'] = 'import',
				['hash'] = `412`,
				['shop'] = 'pdm',
			},
			['488gtb'] = {
				['name'] = '488gtb',
				['brand'] = 'ferrari',
				['model'] = '488gtb',
				['price'] = 255000,
				['category'] = 'import',
				['hash'] = `488gtb`,
				['shop'] = 'pdm',
			},
			['4881'] = {
				['name'] = '4881',
				['brand'] = 'ferrari',
				['model'] = '4881',
				['price'] = 255000,
				['category'] = 'import',
				['hash'] = `4881`,
				['shop'] = 'pdm',
			},
			['f812'] = {
				['name'] = 'f812',
				['brand'] = 'ferrari',
				['model'] = 'f812',
				['price'] = 330000,
				['category'] = 'import',
				['hash'] = `f812`,
				['shop'] = 'pdm',
			},
			['fer612'] = {
				['name'] = 'fer612',
				['brand'] = 'ferrari',
				['model'] = 'fer612',
				['price'] = 235000,
				['category'] = 'import',
				['hash'] = `fer612`,
				['shop'] = 'pdm',
			},
			['fxxk'] = {
				['name'] = 'fxxk',
				['brand'] = 'ferrari',
				['model'] = 'fxxk',
				['price'] = 2600000,
				['category'] = 'import',
				['hash'] = `fxxk`,
				['shop'] = 'pdm',
			},
	---ford		
			['boss302'] = {
				['name'] = 'boss302',
				['brand'] = 'ford',
				['model'] = 'boss302',
				['price'] = 55000,
				['category'] = 'import',
				['hash'] = `boss302`,
				['shop'] = 'pdm',
			},
			['boss429'] = {
				['name'] = 'boss429',
				['brand'] = 'ford',
				['model'] = 'boss429',
				['price'] = 150000,
				['category'] = 'import',
				['hash'] = `boss429`,
				['shop'] = 'pdm',
			},
			['cobra'] = {
				['name'] = 'cobra',
				['brand'] = 'ford',
				['model'] = 'cobra',
				['price'] = 1500000,
				['category'] = 'import',
				['hash'] = `cobra`,
				['shop'] = 'pdm',
			},
			['FGT'] = {
				['name'] = 'FGT',
				['brand'] = 'ford',
				['model'] = 'FGT',
				['price'] = 150000,
				['category'] = 'import',
				['hash'] = `FGT`,
				['shop'] = 'pdm',
			},
			['gt17'] = {
				['name'] = 'gt17',
				['brand'] = 'ford',
				['model'] = 'gt17',
				['price'] = 300000,
				['category'] = 'import',
				['hash'] = `gt17`,
				['shop'] = 'pdm',
			},
			['mgt'] = {
				['name'] = 'mgt',
				['brand'] = 'ford',
				['model'] = 'mgt',
				['price'] = 90000,
				['category'] = 'import',
				['hash'] = `mgt`,
				['shop'] = 'pdm',
			},
	---honda		
			['civic'] = {
				['name'] = 'civic',
				['brand'] = 'honda',
				['model'] = 'civic',
				['price'] = 20000,
				['category'] = 'import',
				['hash'] = `civic`,
				['shop'] = 'pdm',
			},
			['dc2'] = {
				['name'] = 'dc2',
				['brand'] = 'honda',
				['model'] = 'dc2',
				['price'] = 23000,
				['category'] = 'import',
				['hash'] = `dc2`,
				['shop'] = 'pdm',
			},
			['dc5'] = {
				['name'] = 'dc5',
				['brand'] = 'honda',
				['model'] = 'dc5',
				['price'] = 33000,
				['category'] = 'import',
				['hash'] = `dc5`,
				['shop'] = 'pdm',
			},
			['filthynsx'] = {
				['name'] = 'filthynsx',
				['brand'] = 'honda',
				['model'] = 'filthynsx',
				['price'] = 500000,
				['category'] = 'import',
				['hash'] = `filthynsx`,
				['shop'] = 'pdm',
			},
			['fk8'] = {
				['name'] = 'fk8',
				['brand'] = 'honda',
				['model'] = 'fk8',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `fk8`,
				['shop'] = 'pdm',
			},
			['na1'] = {
				['name'] = 'na1',
				['brand'] = 'honda',
				['model'] = 'na1',
				['price'] = 65000,
				['category'] = 'import',
				['hash'] = `na1`,
				['shop'] = 'pdm',
			},
			['nc1'] = {
				['name'] = 'nc1',
				['brand'] = 'honda',
				['model'] = 'nc1',
				['price'] = 170000,
				['category'] = 'import',
				['hash'] = `nc1`,
				['shop'] = 'pdm',
			},
			['ody18'] = {
				['name'] = 'ody18',
				['brand'] = 'honda',
				['model'] = 'ody18',
				['price'] = 37000,
				['category'] = 'import',
				['hash'] = `ody18`,
				['shop'] = 'pdm',
			},
	---hyundai		
			['veln'] = {
				['name'] = 'veln',
				['brand'] = 'hyundai',
				['model'] = 'veln',
				['price'] = 40000,
				['category'] = 'import',
				['hash'] = `veln`,
				['shop'] = 'pdm',
			},
	---jaguar		
			['fpacehm'] = {
				['name'] = 'fpacehm',
				['brand'] = 'jaguar',
				['model'] = 'fpacehm',
				['price'] = 90000,
				['category'] = 'import',
				['hash'] = `fpacehm`,
				['shop'] = 'pdm',
			},
			['jagxjs80'] = {
				['name'] = 'jagxjs80',
				['brand'] = 'jaguar',
				['model'] = 'jagxjs80',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `jagxjs80`,
				['shop'] = 'pdm',
			},
			['p7'] = {
				['name'] = 'p7',
				['brand'] = 'jaguar',
				['model'] = 'p7',
				['price'] = 165000,
				['category'] = 'import',
				['hash'] = `p7`,
				['shop'] = 'pdm',
			},
			['xkgt'] = {
				['name'] = 'xkgt',
				['brand'] = 'jaguar',
				['model'] = 'xkgt',
				['price'] = 135000,
				['category'] = 'import',
				['hash'] = `xkgt`,
				['shop'] = 'pdm',
			},
	---jeep		
			['demonhawk'] = {
				['name'] = 'demonhawk',
				['brand'] = 'jeep',
				['model'] = 'demonhawk',
				['price'] = 110000,
				['category'] = 'import',
				['hash'] = `demonhawk`,
				['shop'] = 'pdm',
			},
			['gladiator'] = {
				['name'] = 'gladiator',
				['brand'] = 'jeep',
				['model'] = 'gladiator',
				['price'] = 65000,
				['category'] = 'import',
				['hash'] = `gladiator`,
				['shop'] = 'pdm',
			},
	---koenigsegg		
			['KoenigseggAgeraR'] = {
				['name'] = 'KoenigseggAgeraR',
				['brand'] = 'Koenigsegg',
				['model'] = 'KoenigseggAgeraR',
				['price'] = 1500000,
				['category'] = 'import',
				['hash'] = `KoenigseggAgeraR`,
				['shop'] = 'pdm',
			},
	---lamborghini		
			['500gtrlam'] = {
				['name'] = '500gtrlam',
				['brand'] = 'lamborghini',
				['model'] = '500gtrlam',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `500gtrlam`,
				['shop'] = 'pdm',
			},
			['610lb'] = {
				['name'] = '610lb',
				['brand'] = 'lamborghini',
				['model'] = '610lb',
				['price'] = 260000,
				['category'] = 'import',
				['hash'] = `610lb`,
				['shop'] = 'pdm',
			},
			['lp700'] = {
				['name'] = 'lp700',
				['brand'] = 'lamborghini',
				['model'] = 'lp700',
				['price'] = 385000,
				['category'] = 'import',
				['hash'] = `lp700`,
				['shop'] = 'pdm',
			},
	---lancia		
			['deltaintegrale'] = {
				['name'] = 'deltaintegrale',
				['brand'] = 'lancia',
				['model'] = 'deltaintegrale',
				['price'] = 51000,
				['category'] = 'import',
				['hash'] = `deltaintegrale`,
				['shop'] = 'pdm',
			},
	---lexus		
			['gx460'] = {
				['name'] = 'gx460',
				['brand'] = 'lexus',
				['model'] = 'gx460',
				['price'] = 75000,
				['category'] = 'import',
				['hash'] = `gx460`,
				['shop'] = 'pdm',
			},
			['lx470'] = {
				['name'] = 'lx470',
				['brand'] = 'lexus',
				['model'] = 'lx470',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `lx470`,
				['shop'] = 'pdm',
			},
	---lotus		
			['carlton'] = {
				['name'] = 'carlton',
				['brand'] = 'lotus',
				['model'] = 'carlton',
				['price'] = 67000,
				['category'] = 'import',
				['hash'] = `carlton`,
				['shop'] = 'pdm',
			},
			['cortina'] = {
				['name'] = 'cortina',
				['brand'] = 'lotus',
				['model'] = 'cortina',
				['price'] = 55000,
				['category'] = 'import',
				['hash'] = `cortina`,
				['shop'] = 'pdm',
			},
	---mazda		
			['fc3s'] = {
				['name'] = 'fc3s',
				['brand'] = 'mazda',
				['model'] = 'fc3s',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `fc3s`,
				['shop'] = 'pdm',
			},
			['fd'] = {
				['name'] = 'fd',
				['brand'] = 'mazda',
				['model'] = 'fd',
				['price'] = 55000,
				['category'] = 'import',
				['hash'] = `fd`,
				['shop'] = 'pdm',
			},
			['fd3s'] = {
				['name'] = 'fd3s',
				['brand'] = 'mazda',
				['model'] = 'fd3s',
				['price'] = 49000,
				['category'] = 'import',
				['hash'] = `fd3s`,
				['shop'] = 'pdm',
			},
	---mercedesbenz		
			['500w124'] = {
				['name'] = '500w124',
				['brand'] = 'mercedesbenz',
				['model'] = '500w124',
				['price'] = 45000,
				['category'] = 'import',
				['hash'] = `500w124`,
				['shop'] = 'pdm',
			},
			['722s'] = {
				['name'] = '722s',
				['brand'] = 'mercedesbenz',
				['model'] = '722s',
				['price'] = 1300000,
				['category'] = 'import',
				['hash'] = `722s`,
				['shop'] = 'pdm',
			},
			['a45amg'] = {
				['name'] = 'a45amg',
				['brand'] = 'mercedesbenz',
				['model'] = 'a45amg',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `a45amg`,
				['shop'] = 'pdm',
			},
			['AMGCEW'] = {
				['name'] = 'AMGCEW',
				['brand'] = 'mercedesbenz',
				['model'] = 'AMGCEW',
				['price'] = 55000,
				['category'] = 'import',
				['hash'] = `AMGCEW`,
				['shop'] = 'pdm',
			},
			['b63s'] = {
				['name'] = 'b63s',
				['brand'] = 'mercedesbenz',
				['model'] = 'b63s',
				['price'] = 150000,
				['category'] = 'import',
				['hash'] = `b63s`,
				['shop'] = 'pdm',
			},
			['brabus850'] = {
				['name'] = 'brabus850',
				['brand'] = 'mercedesbenz',
				['model'] = 'brabus850',
				['price'] = 145000,
				['category'] = 'import',
				['hash'] = `brabus850`,
				['shop'] = 'pdm',
			},
			['CLS53'] = {
				['name'] = 'CLS53',
				['brand'] = 'mercedesbenz',
				['model'] = 'CLS53',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `CLS53`,
				['shop'] = 'pdm',
			},
			['e55'] = {
				['name'] = 'e55',
				['brand'] = 'mercedesbenz',
				['model'] = 'e55',
				['price'] = 60000,
				['category'] = 'import',
				['hash'] = `e55`,
				['shop'] = 'pdm',
			},
			['g65amg'] = {
				['name'] = 'g65amg',
				['brand'] = 'mercedesbenz',
				['model'] = 'g65amg',
				['price'] = 105000,
				['category'] = 'import',
				['hash'] = `g65amg`,
				['shop'] = 'pdm',
			},
			['W140s600'] = {
				['name'] = 'W140s600',
				['brand'] = 'mercedesbenz',
				['model'] = 'W140s600',
				['price'] = 67000,
				['category'] = 'import',
				['hash'] = `W140s600`,
				['shop'] = 'pdm',
			},
	---mitsubishi		
			['cp9a'] = {
				['name'] = 'cp9a',
				['brand'] = 'mitsubishi',
				['model'] = 'cp9a',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `cp9a`,
				['shop'] = 'pdm',
			},
			['evo9'] = {
				['name'] = 'evo9',
				['brand'] = 'mitsubishi',
				['model'] = 'evo9',
				['price'] = 58000,
				['category'] = 'import',
				['hash'] = `evo9`,
				['shop'] = 'pdm',
			},
			['evo9mr'] = {
				['name'] = 'evo9mr',
				['brand'] = 'mitsubishi',
				['model'] = 'evo9mr',
				['price'] = 58000,
				['category'] = 'import',
				['hash'] = `evo9mr`,
				['shop'] = 'pdm',
			},
	---motorcycle		
			['bmws'] = {
				['name'] = 'bmws',
				['brand'] = 'bmw',
				['model'] = 'bmws',
				['price'] = 17000,
				['category'] = 'import',
				['hash'] = `bmws`,
				['shop'] = 'pdm',
			},
			['g_xlcr'] = {
				['name'] = 'g_xlcr',
				['brand'] = 'harleydavidson',
				['model'] = 'g_xlcr',
				['price'] = 12000,
				['category'] = 'import',
				['hash'] = `g_xlcr`,
				['shop'] = 'pdm',
			},
			['na25'] = {
				['name'] = 'na25',
				['brand'] = 'xxx',
				['model'] = 'na25',
				['price'] = 13500,
				['category'] = 'import',
				['hash'] = `na25`,
				['shop'] = 'pdm',
			},
			['r6'] = {
				['name'] = 'r6',
				['brand'] = 'yamaha',
				['model'] = 'r6',
				['price'] = 12000,
				['category'] = 'import',
				['hash'] = `r6`,
				['shop'] = 'pdm',
			},
			['rmz2'] = {
				['name'] = 'rmz2',
				['brand'] = 'suzuki',
				['model'] = 'rmz2',
				['price'] = 9000,
				['category'] = 'import',
				['hash'] = `rmz2`,
				['shop'] = 'pdm',
			},
	---nissan		
			['bnr34'] = {
				['name'] = 'bnr34',
				['brand'] = 'nissan',
				['model'] = 'bnr34',
				['price'] = 69000,
				['category'] = 'import',
				['hash'] = `bnr34`,
				['shop'] = 'pdm',
			},
			['r32'] = {
				['name'] = 'r32',
				['brand'] = 'nissan',
				['model'] = 'r32',
				['price'] = 63000,
				['category'] = 'import',
				['hash'] = `r32`,
				['shop'] = 'pdm',
			},
			['r35'] = {
				['name'] = 'r35',
				['brand'] = 'nissan',
				['model'] = 'r35',
				['price'] = 115000,
				['category'] = 'import',
				['hash'] = `r35`,
				['shop'] = 'pdm',
			},
			['s15'] = {
				['name'] = 's15',
				['brand'] = 'nissan',
				['model'] = 's15',
				['price'] = 55000,
				['category'] = 'import',
				['hash'] = `s15`,
				['shop'] = 'pdm',
			},
			['s30'] = {
				['name'] = 's30',
				['brand'] = 'nissan',
				['model'] = 's30',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `s30`,
				['shop'] = 'pdm',
			},
			['skylinec110'] = {
				['name'] = 'skylinec110',
				['brand'] = 'nissan',
				['model'] = 'skylinec110',
				['price'] = 56000,
				['category'] = 'import',
				['hash'] = `skylinec110`,
				['shop'] = 'pdm',
			},
	---pagani		
			['bc'] = {
				['name'] = 'bc',
				['brand'] = 'pagani',
				['model'] = 'bc',
				['price'] = 2300000,
				['category'] = 'import',
				['hash'] = `bc`,
				['shop'] = 'pdm',
			},
			['huayrar'] = {
				['name'] = 'huayrar',
				['brand'] = 'pagani',
				['model'] = 'huayrar',
				['price'] = 2500000,
				['category'] = 'import',
				['hash'] = `huayrar`,
				['shop'] = 'pdm',
			},
	---peugeot		
			['205'] = {
				['name'] = '205',
				['brand'] = 'peugeot',
				['model'] = '205',
				['price'] = 19000,
				['category'] = 'import',
				['hash'] = `205`,
				['shop'] = 'pdm',
			},
			['polschafter3'] = {
				['name'] = 'polschafter3',
				['brand'] = 'police',
				['model'] = 'polschafter3',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `polschafter3`,
				['shop'] = 'pdm',
			},
			['sheriff'] = {
				['name'] = 'sheriff',
				['brand'] = 'police',
				['model'] = 'sheriff',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `sheriff`,
				['shop'] = 'pdm',
			},
			['sspres'] = {
				['name'] = 'sspres',
				['brand'] = 'police',
				['model'] = 'sspres',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `sspres`,
				['shop'] = 'pdm',
			},
	---porshce		
			['356ac'] = {
				['name'] = '356ac',
				['brand'] = 'porsche',
				['model'] = '356ac',
				['price'] = 60000,
				['category'] = 'import',
				['hash'] = `356ac`,
				['shop'] = 'pdm',
			},
			['macan'] = {
				['name'] = 'macan',
				['brand'] = 'porsche',
				['model'] = 'macan',
				['price'] = 80000,
				['category'] = 'import',
				['hash'] = `macan`,
				['shop'] = 'pdm',
			},
			['panamera17turbo'] = {
				['name'] = 'panamera17turbo',
				['brand'] = 'porsche',
				['model'] = 'panamera17turbo',
				['price'] = 130000,
				['category'] = 'import',
				['hash'] = `panamera17turbo`,
				['shop'] = 'pdm',
			},
			['SingerDLS'] = {
				['name'] = 'SingerDLS',
				['brand'] = 'porsche',
				['model'] = 'SingerDLS',
				['price'] = 85000,
				['category'] = 'import',
				['hash'] = `SingerDLS`,
				['shop'] = 'pdm',
			},
	---landrover		
			['rr12'] = {
				['name'] = 'rr12',
				['brand'] = 'landrover',
				['model'] = 'rr12',
				['price'] = 62000,
				['category'] = 'import',
				['hash'] = `rr12`,
				['shop'] = 'pdm',
			},
	---renault		
			['clio'] = {
				['name'] = 'clio',
				['brand'] = 'renault',
				['model'] = 'clio',
				['price'] = 20000,
				['category'] = 'import',
				['hash'] = `clio`,
				['shop'] = 'pdm',
			},
			['f1'] = {
				['name'] = 'f1',
				['brand'] = 'renault',
				['model'] = 'f1',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `f1`,
				['shop'] = 'pdm',
			},
	---rollsroyce		
			['silver67'] = {
				['name'] = 'silver67',
				['brand'] = 'rollsroyce',
				['model'] = 'silver67',
				['price'] = 100000,
				['category'] = 'import',
				['hash'] = `silver67`,
				['shop'] = 'pdm',
			},
			['wraith'] = {
				['name'] = 'wraith',
				['brand'] = 'rollsroyce',
				['model'] = 'wraith',
				['price'] = 320000,
				['category'] = 'import',
				['hash'] = `wraith`,
				['shop'] = 'pdm',
			},
	---subaru		
			['wrx15'] = {
				['name'] = 'wrx15',
				['brand'] = 'subaru',
				['model'] = 'wrx15',
				['price'] = 65000,
				['category'] = 'import',
				['hash'] = `wrx15`,
				['shop'] = 'pdm',
			},
	---toyota		
			['wraith'] = {
				['name'] = 'a80',
				['brand'] = 'toyota',
				['model'] = 'a80',
				['price'] = 68000,
				['category'] = 'import',
				['hash'] = `a80`,
				['shop'] = 'pdm',
			},
			['cam8tun'] = {
				['name'] = 'cam8tun',
				['brand'] = 'toyota',
				['model'] = 'cam8tun',
				['price'] = '50000',
				['category'] = 'import',
				['hash'] = `wraith`,
				['shop'] = 'pdm',
			},
			['jzx100'] = {
				['name'] = 'jzx100',
				['brand'] = 'toyota',
				['model'] = 'jzx100',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `jzx100`,
				['shop'] = 'pdm',
			},
			['prius'] = {
				['name'] = 'prius',
				['brand'] = 'toyota',
				['model'] = 'prius',
				['price'] = 38000,
				['category'] = 'import',
				['hash'] = `prius`,
				['shop'] = 'pdm',
			},
			['toyotasj'] = {
				['name'] = 'toyotasj',
				['brand'] = 'toyota',
				['model'] = 'toyotasj',
				['price'] = 70000,
				['category'] = 'import',
				['hash'] = `toyotasj`,
				['shop'] = 'pdm',
			},
			['sjtoyota'] = {
				['name'] = 'sjtoyota',
				['brand'] = 'toyota',
				['model'] = 'sjtoyota',
				['price'] = 95000,
				['category'] = 'import',
				['hash'] = `sjtoyota`,
				['shop'] = 'pdm',
			},
	---truck		
			['actros'] = {
				['name'] = 'actros',
				['brand'] = 'truck',
				['model'] = 'actros',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `actros`,
				['shop'] = 'pdm',
			},
			['daf'] = {
				['name'] = 'daf',
				['brand'] = 'truck',
				['model'] = 'daf',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `daf`,
				['shop'] = 'pdm',
			},
			['man'] = {
				['name'] = 'man',
				['brand'] = 'truck',
				['model'] = 'man',
				['price'] = 5000000,
				['category'] = 'import',
				['hash'] = `man`,
				['shop'] = 'pdm',
			},
	---volvo		
			['s60pole'] = {
				['name'] = 's60pole',
				['brand'] = 'volvo',
				['model'] = 's60pole',
				['price'] = 50000,
				['category'] = 'import',
				['hash'] = `s60pole`,
				['shop'] = 'pdm',
			},
			['volvo145'] = {
				['name'] = 'volvo145',
				['brand'] = 'volvo',
				['model'] = 'volvo145',
				['price'] = 18000,
				['category'] = 'import',
				['hash'] = `volvo145`,
				['shop'] = 'pdm',
			},

			['s60pole'] = {
				['name'] = 'volvo850r',
				['brand'] = 'volvo',
				['model'] = 'volvo850r',
				['price'] = 40000,
				['category'] = 'import',
				['hash'] = `volvo850r`,
				['shop'] = 'pdm',
			},
